string_kind!(
    /// Semantic role of a graph node.
    NodeKind,
    "node",
    {
        Repository => "repository",
        File => "file",
        Module => "module",
        Package => "package",
        Function => "function",
        Method => "method",
        Struct => "struct",
        Enum => "enum",
        Trait => "trait",
        TypeAlias => "type_alias",
        Constant => "constant",
        Static => "static",
        Service => "service",
        Endpoint => "endpoint",
        Table => "table",
        Column => "column",
        Topic => "topic",
        ConsumerGroup => "consumer_group",
        Exchange => "exchange",
        Queue => "queue",
        Binding => "binding",
        Collection => "collection",
        Index => "index",
        KubernetesResource => "kubernetes_resource",
        Container => "container",
        ConfigKey => "config_key",
        Unknown => "unknown",
    }
);
